/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afleurdeuxpots802.pages.panier;

import afleurdeuxpots802.header.Header;
import afleurdeuxpots802.header.IHeaderHolder;
import afleurdeuxpots802.model.Product;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;

/**
 *
 * @author guilhem
 */
public class PanierPage extends javax.swing.JFrame implements IHeaderHolder{
    
    private final PropertyChangeSupport support;

    /**
     * Creates new form PanierPage
     */
    public PanierPage() {
        initComponents();
        support = new PropertyChangeSupport(this);
        productView1.hideButton();
        productView1.setVisible(false);
        priceProductLabel.setVisible(false);
        header1.setFull(true);
    }
    
    @Override
    public void addHeaderCallback(String name, PropertyChangeListener li){
        header1.addPropertyChangeListener(name, li);
    }
    
    @Override
    public void removeHeaderCallback(String name, PropertyChangeListener li){
        header1.removePropertyChangeListener(name, li);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        header1 = new afleurdeuxpots802.header.Header();
        productView1 = new afleurdeuxpots802.pages.content.view.ProductView();
        jLabel2 = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        priceProductLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mon Panier");

        header1.setFull(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Total :");

        totalPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalPriceLabel.setText("0 €");

        priceProductLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        priceProductLabel.setText("54,34 €");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("Commander");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                    .addComponent(header1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productView1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceProductLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(75, 75, 75)
                                .addComponent(totalPriceLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(productView1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(priceProductLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalPriceLabel))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        support.firePropertyChange(String.valueOf(Panier.COMMANDE_CLICKED_SIGNAL), null, null);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void addPropertyChangeListener(String name, PropertyChangeListener li){
        support.addPropertyChangeListener(name, li);
    }
    
    public void removePropertyChangeListener (String name, PropertyChangeListener li){
        support.removePropertyChangeListener(name, li);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private afleurdeuxpots802.header.Header header1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel priceProductLabel;
    private afleurdeuxpots802.pages.content.view.ProductView productView1;
    private javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setFull(boolean b) {
        header1.setFull(b);
        jButton1.setEnabled(b);
    }

    void setProduct(Product product) {
        productView1.setName(product.getName());
        productView1.setImage(product.getImagePath());
        productView1.setPrice(product.getPrice());
        productView1.setVisible(true);
        priceProductLabel.setVisible(true);
        totalPriceLabel.setText("54,34 €");
    }
}
