/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afleurdeuxpots802.header;

import java.awt.BorderLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author buisangu
 */
public class Header extends javax.swing.JPanel {
    
    private JMenuBar menuBar;
    public final static int ACCUEIL_CLICKED_SIGNAL = 0;
    public final static int ST_VALENTIN_CLICKED_SIGNAL = 1;
    private final PropertyChangeSupport support;

    /**
     * Creates new form Header
     */
    public Header() {
        support = new PropertyChangeSupport(this);
        System.out.println(support);
        initComponents();
        
        
        menuBar = new JMenuBar();
        JMenuItem stVal = new JMenuItem("Saint Valentin");
        stVal.addActionListener((e) -> {
            support.firePropertyChange(String.valueOf(ST_VALENTIN_CLICKED_SIGNAL), null, null);
        });
        menuBar.add(stVal);
        JMenu cata = new JMenu("Catalogue");
        JMenuItem catarose = new JMenuItem("Roses");
        JMenuItem catatulipe = new JMenuItem("Tulipes");
        JMenuItem catalys = new JMenuItem("Lys");
        JMenuItem catabonzai = new JMenuItem("Bonzai");
        cata.add(catarose);
        cata.add(catatulipe);
        cata.add(catalys);
        cata.add(catabonzai);
        menuBar.add(cata);
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(menuBar, BorderLayout.NORTH);
        
        jLabel1.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                support.firePropertyChange(String.valueOf(ACCUEIL_CLICKED_SIGNAL), null, null);
            }

            @Override
            public void mousePressed(MouseEvent e) {
                //Rien
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                //Rien
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                //Rien
            }

            @Override
            public void mouseExited(MouseEvent e) {
                //Rien
            }
        });
        
    }
    @Override
    public void addPropertyChangeListener(String name, PropertyChangeListener li){
        support.addPropertyChangeListener(name, li);
    }
    @Override
    public void removePropertyChangeListener(PropertyChangeListener li){
        support.removePropertyChangeListener(li);
    }
    @Override
    public void removePropertyChangeListener(String name, PropertyChangeListener li){
        support.removePropertyChangeListener(name, li);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1360, 440));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/afleurdeuxpots802/header/AFDP.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/afleurdeuxpots802/header/Panier vide.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 562, Short.MAX_VALUE)
                .addComponent(jLabel2))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
