/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afleurdeuxpots802.widgets;

import afleurdeuxpots802.controller.Controller;
import afleurdeuxpots802.model.Product;
import afleurdeuxpots802.widgets.ProductView;

/**
 *
 * @author fabien
 */
public class ContentPanel extends javax.swing.JPanel {
    
    private Controller controller;
    /**
     * Creates new form ContentPanel
     */
    public ContentPanel() {
        initComponents();
        //nextPageThumbnail.setAsNext();
        nextPageThumbnail.setAsPrev();
    }
    
    public void setController(Controller controller) {
        this.controller = controller;
    }
    
    public void setProduct(int i, Product product) {
        ProductView[] productViews = {productView1, productView2};
        if(i<0 || i>= productViews.length) {
            return;
        }
        ProductView productView = productViews[i];
        
        if(product == null) {
            productView.setVisible(false);
        } else {
            productView.setName(product.getName());
            productView.setImage(product.getImagePath());
            productView.setPrice(product.getPrice());
            productView.setVisible(true);
        }
    }
    
    public void setNextPageThumbnail(int i, Product product) {
        nextPageThumbnail.setThumbnail(i, product);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productView1 = new afleurdeuxpots802.widgets.ProductView();
        productView2 = new afleurdeuxpots802.widgets.ProductView();
        nextPageThumbnail = new afleurdeuxpots802.widgets.PageThumbnail();

        nextPageThumbnail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextPageThumbnailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(productView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nextPageThumbnail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(nextPageThumbnail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextPageThumbnailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPageThumbnailMouseClicked
        ViewEvent viewEvent = new ViewEvent(ViewEventType.NEXT_PAGE);
        controller.handleEvent(viewEvent);
        System.out.println("clicked");
    }//GEN-LAST:event_nextPageThumbnailMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private afleurdeuxpots802.widgets.PageThumbnail nextPageThumbnail;
    private afleurdeuxpots802.widgets.ProductView productView1;
    private afleurdeuxpots802.widgets.ProductView productView2;
    // End of variables declaration//GEN-END:variables

    public void setNextPagesNumber(int nbNextPages) {
        nextPageThumbnail.setNextPageNumber(nbNextPages);
    }
    
    public void setPrevPageNumber(int nbPrevPages) {
        //prevPageThumbnail.setPrevPageNumber(nbPrevPages);
    }

}
