/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package afleurdeuxpots802.pages.content.view;

import afleurdeuxpots802.pages.content.Controller;
import javax.swing.ImageIcon;

/**
 *
 * @author fabien
 */
public class ProductView extends javax.swing.JPanel {

    private static final String PATH_NO_IMAGE = "./ressources/noImage.png";
    private Controller controller;
    private int no;
    /**
     * Creates new form ProductView
     */
    public ProductView() {
        initComponents();
    }
    
    public void setController(Controller controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        addToCartButton = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();

        nameLabel.setText("Name");

        priceLabel.setText("0,00 €");

        addToCartButton.setText("Buy");
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });

        imgLabel.setText("IMG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(priceLabel)
                                .addGap(18, 18, 18)
                                .addComponent(addToCartButton))
                            .addComponent(nameLabel))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(addToCartButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        ViewEvent viewEvent = new ViewEvent(ViewEventType.ADD_TO_CART, no);
        controller.handleEvent(viewEvent);
    }//GEN-LAST:event_addToCartButtonActionPerformed

    public void setImage(String path) {
        if(path != null) {
            //ImageIcon icon = new ImageIcon(path);
            ImageIcon icon = new ImageIcon((new ImageIcon(path)).getImage().getScaledInstance(150, 150,  java.awt.Image.SCALE_SMOOTH));
            imgLabel.setText("");
            imgLabel.setIcon(icon);
        } else {
            ImageIcon icon = new ImageIcon((new ImageIcon(PATH_NO_IMAGE)).getImage().getScaledInstance(150, 150,  java.awt.Image.SCALE_SMOOTH));
            imgLabel.setText("");
            imgLabel.setIcon(icon);
        }
        
        
    }
    
    public void setName(String name) {
        if(name != null) {
            nameLabel.setText(name);
        }
    }
    
    public void setNo(int no) {
        this.no = no;
    }
    
    public void setPrice(Double price) {
        if(price != null) {
            priceLabel.setText(price + " €");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartButton;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables

    void enableBuy(boolean b) {
        this.addToCartButton.setEnabled(b);
    }
}
